export const COLUMN_KEYS = {
  collaborator: "Collaborateur",
  pinKey: "Clé (PIN)",
  sector: "Location\nphysical location on floor",
  prodsched: "Prodsched",
  stationName: "Manufacturing Station names",
  lastInventoryDate: "Date",
  assetType: "Type of equipment\n(PLC, Sensor, ComXboX)",
  manufacturer: "Brand",
  model: "Model",
  serialNumber: "Serial Number",
  storage: "HDD",
  hostname: "Hostname",
  sap: "SAP",
  operatingSystem: "OS Type",
  macAddress: "MAC Address 1",
  ipAddress: "IP address 1",
  subnetMask: "Subnet 1",
  vlan: "VLAN id/name",
  networkScope: "VLAN Name",
  oldIpAddress: "Old IP address",
  newIpAddress: "New IP address ",
  vlanNew: "VLAN New",
  idPort: "ID PORT",
  newPortAuto: "New PORT AUTO",
  switchName: "NOM SWITCH",
  switchIpAddress: "IP SWITCH",
  ticketBrassage: "Ticket Brassage",
  ipFilter: "Filtre IP",
  etat: "Etat",
  connectedToSwitchName: "Connected to SWITCH Name ",
  connectedToSwitchPort: "Connected to SWITCH Port",
  wifiOrWiredConnection: "WiFi or Wired Connection",
  directoryAccount: "Login",
  gateway: "Passerelle",
  comment: "Commentaire",
  commentaire2: "Commentaire2",
  securityStatus: "McAfee Client Installed",
} as const;

export const PC_ASSET_TYPE = "PC";
